# Site Data
title: Notes on the Summa Theoludica
tagline: 
name: 
author_bio: >
footer_description: >
notes_url: https://mwmxyz.github.io/manuscript
profile_pic: 
favicon: https://mwmxyz.github.io/manuscript/assets/img/favicon.png
baseurl: "/manuscript" # the subpath of your site, e.g. /blog
url: "https://mwmxyz.github.io"     # the base hostname & protocol for your site, e.g. https://example.com
theme_color: white
encoding: utf-8

# Links and Social Media
donate_link: 
repository: https://mwmxyz.github.io/manuscript
github: 
twitter: 
portfolio: 
email: michael.merriam@ucf.edu

# Build Settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-minifier
  - jekyll-toc

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

JEKYLL_ENV: "production"

collections:
  notes:
    output: true
    permalink: https://mwmxyz.github.io/manuscript/notes/:title
  journals:
    output: true
    permalink: https://mwmxyz.github.io/manuscript/journals/:title
  pages:
    output: true
    permalink: https://mwmxyz.github.io/manuscript/page/:name

disqus:
  shortname: 

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: https://mwmxyz.github.io/manuscript/posts/:title
      content-type: post
      category: "Post"
      toc: true
  - scope:
      path: "https://mwmxyz.github.io/manuscript"
      type: notes
    values:
      layout: post
      content-type: notes
  - scope:
      path: "https://mwmxyz.github.io/manuscript"
      type: journals
    values:
      layout: post
      content-type: journals
  - scope:
      path: "https://mwmxyz.github.io/manuscript"
      type: pages
    values:
      layout: page
      content-type: pages

jekyll-archives:
  enabled: []
  layout: default
  permalinks:
    year: "https://mwmxyz.github.io/manuscript/:year/"
    month: "https://mwmxyz.github.io/manuscript/:year/:month/"
    day: "https://mwmxyz.github.io/manuscript/:year/:month/:day/"
    tag: "https://mwmxyz.github.io/manuscript/tag/:name/"
    category: "https://mwmxyz.github.io/manuscript/category/:name/"

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no-toc
  list_class: section-nav
  sublist_class: ""
  item_class: entry
  item_prefix: toc-
